In [8]:
import torch
import numpy as np

In [9]:
t = torch.tensor([[1., -1.], [1., -1.]])
t2 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(t)
print(t2)

tensor([[ 1., -1.],
        [ 1., -1.]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [12]:
t3 = torch.zeros([2, 4], dtype=torch.int32)
t4 = torch.ones([2, 4], dtype=torch.float64)
print(t3)
print(t4)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


##### try torch.float32, torch.float64, torch.uint8, torch.int32