Numpy 範例程式碼

In [1]:
! pip install numpy


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a = np.array([2,5,4,3])
b = np.array((3,6,5,4))
print(a,b)
print(type(a), type(b))

[2 5 4 3] [3 6 5 4]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [4]:
a = np.zeros([2, 5])
print("a:",a)
b = np.ones([2, 5])
print("b:",b)

a: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
b: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
a = np.array([[1, 2, 4],[3, 2, 5],[1, 5, 6]])
print("Size: ", a.size)
print("Dimension: ", a.ndim)

Size:  9
Dimension:  2


In [6]:
a = np.arange(1,17, 2)
a = a.reshape(2,4)
print(a)

[[ 1  3  5  7]
 [ 9 11 13 15]]


In [7]:
a = np.arange(1,17, 1)
print("Before Reshape: ",a)
a = a.reshape(4,4)
print("After Reshape:\n", a)

Before Reshape:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
After Reshape:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
a = np.arange(1,17, 1)
a = a.reshape(4,4)
print("a",a)
print("---")
print("a[1,2]:\n",a[1,2])
print("a[0,:]:\n",a[0,:]) 
print("a[:,0]:\n",a[:,0])

a [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
---
a[1,2]:
 7
a[0,:]:
 [1 2 3 4]
a[:,0]:
 [ 1  5  9 13]


In [9]:
a = np.arange(1,17, 1)
a = a.reshape(4,4)
print("Before add:\n", a)
a = a+1 # 將所有的元素都加上1
print("After add:\n",a)
a = a**2  # 將所有的元素都平方
print("After square:\n", a)

Before add:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
After add:
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
After square:
 [[  4   9  16  25]
 [ 36  49  64  81]
 [100 121 144 169]
 [196 225 256 289]]


In [10]:
a = np.arange(1,5, 1)
a = a.reshape(2,2)
b = np.arange(5,9, 1)
b = b.reshape(2,2)
print("sum：\n",a+b)
print("multiply: \n", a*b)

sum：
 [[ 6  8]
 [10 12]]
multiply: 
 [[ 5 12]
 [21 32]]


In [11]:
a = np.arange(1,5, 1)
a = a.reshape(2,2)
b = np.arange(5,9, 1)
b = b.reshape(2,2)
print(np.dot(a,b))

[[19 22]
 [43 50]]
