In [2]:
import torch
import numpy as np

In [3]:
a = torch.tensor([[1,-1],[1,-1]]) 
print(a)
b = torch.tensor(np.array([[1, 2, 3],[1,-2, -3]]))
print(b)

tensor([[ 1, -1],
        [ 1, -1]])
tensor([[ 1,  2,  3],
        [ 1, -2, -3]])


In [4]:
a = torch.ones([2, 3], dtype=torch.float64)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [5]:
b = torch.zeros([2, 3], dtype=torch.float64)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [6]:
a = torch.ones([2, 3], dtype=torch.float64)
b = torch.zeros([2, 3], dtype=torch.float64) 
c = torch.stack([a,b], dim=0)
print(c)
print(c.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)
torch.Size([2, 2, 3])


In [7]:
a = torch.ones([2, 3], dtype=torch.float64)
b = torch.zeros([2, 3], dtype=torch.float64) 
c = torch.stack([a,b], dim=1)
print(c)
print(c.shape)

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]], dtype=torch.float64)
torch.Size([2, 2, 3])


In [8]:
c = torch.stack([a,b], dim=2)
print(c)
print(c.shape)

tensor([[[1., 0.],
         [1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.],
         [1., 0.]]], dtype=torch.float64)
torch.Size([2, 3, 2])


In [9]:
d = torch.concat([a,b])
print(d)
print(d.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
torch.Size([4, 3])


In [10]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x)
print(x.shape)

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
torch.Size([2, 1, 2, 1, 2])


In [11]:
y = torch.squeeze(x)
print(y)
print(y.shape)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([2, 2, 2])


In [12]:
y = torch.squeeze(x, 0)
print(y.shape)

torch.Size([2, 1, 2, 1, 2])


In [13]:
y = torch.squeeze(x, 3)
print(y.shape)

torch.Size([2, 1, 2, 2])


In [14]:
x = torch.tensor([1, 2, 3, 4])
y = torch.unsqueeze(x, 0)
print(y)
print(y.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


In [15]:
y = torch.unsqueeze(x, 1)
print(y)
print(y.shape)

tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [16]:
x = torch.randn(2, 3)
print(x)

tensor([[-0.1253, -0.9807,  0.8326],
        [-0.5440,  0.0942, -0.3283]])


In [17]:
y = torch.transpose(x, 0, 1)
print(y)

tensor([[-0.1253, -0.5440],
        [-0.9807,  0.0942],
        [ 0.8326, -0.3283]])


In [18]:
x = torch.randn(2, 3, 2)
print(x)
print(x.shape)

tensor([[[ 0.3627,  0.5215],
         [ 0.4157, -0.6189],
         [-0.6325,  1.5461]],

        [[ 0.8484, -0.1426],
         [ 0.0172, -0.3315],
         [-1.0579, -0.6987]]])
torch.Size([2, 3, 2])


In [19]:
y = torch.transpose(x, 1, 2)
print(y)
print(y.shape)

tensor([[[ 0.3627,  0.4157, -0.6325],
         [ 0.5215, -0.6189,  1.5461]],

        [[ 0.8484,  0.0172, -1.0579],
         [-0.1426, -0.3315, -0.6987]]])
torch.Size([2, 2, 3])


In [20]:
y = torch.transpose(x, 0, 1)
print(y)
print(y.shape)

tensor([[[ 0.3627,  0.5215],
         [ 0.8484, -0.1426]],

        [[ 0.4157, -0.6189],
         [ 0.0172, -0.3315]],

        [[-0.6325,  1.5461],
         [-1.0579, -0.6987]]])
torch.Size([3, 2, 2])


In [21]:
y = torch.transpose(x, 0, 2)
print(y)
print(y.shape)

tensor([[[ 0.3627,  0.8484],
         [ 0.4157,  0.0172],
         [-0.6325, -1.0579]],

        [[ 0.5215, -0.1426],
         [-0.6189, -0.3315],
         [ 1.5461, -0.6987]]])
torch.Size([2, 3, 2])


In [22]:
a = torch.ones([5, 3], dtype=torch.float64)
b = torch.zeros([5, 3], dtype=torch.float64) 
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [23]:
c = torch.stack([a,b], dim=0)
print(c)
print(c.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)
torch.Size([2, 5, 3])


In [24]:
x = torch.zeros(2, 1, 5, 1, 1, 4)
print(x)
print(x.shape)

tensor([[[[[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]]]],




        [[[[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]],


          [[[0., 0., 0., 0.]]]]]])
torch.Size([2, 1, 5, 1, 1, 4])


In [25]:
print(x.shape)
y = torch.squeeze(x, 1)
print(y.shape)

torch.Size([2, 1, 5, 1, 1, 4])
torch.Size([2, 5, 1, 1, 4])


In [26]:
y = torch.squeeze(torch.squeeze(x, 3), 3)


In [27]:
y = torch.squeeze(x, 4)
y = torch.squeeze(y, 3)
print(y.shape)

torch.Size([2, 1, 5, 4])
